// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wires

import (
	"Week04/internal/Week04/biz"
	"Week04/internal/Week04/data"
	"Week04/internal/Week04/service"
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func InitProductService(db *gorm.DB) *service.ProductService {
	productData := data.NewProductData(db)
	productBiz := biz.NewProductBiz(productData)
	productService := service.NewProductService(productBiz)
	return productService
}
